import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs, initializeFirestore } from 'firebase/firestore';
import fs from 'fs';
const config = JSON.parse(fs.readFileSync('./firebase-applet-config.json'));
const app = initializeApp(config);
const db = initializeFirestore(app, {});
const docs = await getDocs(collection(db, "announcements"));
console.log("Found:", docs.size);
docs.forEach(d => console.log(d.data().title));
process.exit(0);
